C	Copyright Eric Fuller, 2001-2007



	SUBROUTINE PLOT(NDAT,
     *  X1,X2,AFUNC1,AFUNC2,MA,PHI,
     *  A,Z1,Z2,Y1,Y2)

	INCLUDE 'pfit.cmn'



	INTEGER*4 NDAT
	REAL*8 X1(NMAX),X2(NMAX)
	REAL*8 AFUNC1(MMAX),AFUNC2(MMAX)
	INTEGER*4 MA
	REAL*8 PHI,A(MMAX),Z1(NMAX),Z2(NMAX),Y1(NMAX),Y2(NMAX)

	REAL*8 SUM1,SUM2
	INTEGER*4 I,J

	EXTERNAL FUNCS



C	THIS PLOT FILE CONTAINS:
C	  EXPECTED COORDINATES
C	  ACTUAL COORDINATES
C	  CORRECTED COORDINATES, BASED ON EXPECTED AND MODEL
C	  RESIDUALS

	OPEN(UNIT=8,FILE='plot.dat',STATUS='UNKNOWN')

	DO I=1,NDAT
	  CALL FUNCS(X1(I),X2(I),AFUNC1,AFUNC2,MA,PHI)
	  SUM1=0.0
	  SUM2=0.0
	  DO J=1,MA
	    SUM1=SUM1+A(J)*AFUNC1(J)
	    SUM2=SUM2+A(J)*AFUNC2(J)
	    ENDDO
	  Z1(I)=SUM1
	  Z2(I)=SUM2
	  WRITE(8,51) X1(I),X2(I),Y1(I),Y2(I),
     *      Z1(I),Z2(I),Y1(I)-Z1(I),Y2(I)-Z2(I)

	  ENDDO

	CLOSE(8)



51	FORMAT(8(F10.4,2X))

	RETURN
	END



